version: '3'


services:
  db:
    image: postgres
    # ports:
    #   - "5432:5432"
    environment:
      - POSTGRES_DB=rootdb
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_HOST=localhost

  web:
    build: .
    command: python3 main.py
    volumes:
      - .:/app
    ports:
      - "8888:8888"
    depends_on:
      - db